// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_content_delivery_bucket": "mernstak-20200413135300-hostingbucket-nodejs",
    "aws_content_delivery_bucket_region": "us-east-2",
    "aws_content_delivery_url": "https://dxmfonh96c4v5.cloudfront.net"
};


export default awsmobile;
